# Generated by Django 6.0.3 on 2026-03-09 13:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_stock', models.IntegerField()),
                ('product_category', models.CharField(max_length=100)),
            ],
        ),
    ]
